name: sky_watch
description: "A Flutter-based app that provides weather information for multiple locations and offers recommendations based on the current weather."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^13.0.1 # Retrieve device location info via gps
  intl: ^0.19.0 # Date and Time formatter
  flutter_dotenv: ^5.1.0
  logger: ^2.4.0
  google_fonts: ^6.2.1
  cupertino_icons: ^1.0.8
  weather: ^3.1.1 # OpenWeatherMap API wrapper
  hugeicons: ^0.0.7
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true
  assets:
    - .env
